/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icecool_worldinshadow_ActividadOpenAL */

#ifndef _Included_com_icecool_worldinshadow_ActividadOpenAL
#define _Included_com_icecool_worldinshadow_ActividadOpenAL
#ifdef __cplusplus
extern "C" {
#endif
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_PRIVATE
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_PRIVATE 0L
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_WORLD_READABLE
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_WORLD_READABLE 1L
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_WORLD_WRITEABLE
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_WORLD_WRITEABLE 2L
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_APPEND
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_APPEND 32768L
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_MULTI_PROCESS
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_MULTI_PROCESS 4L
#undef com_icecool_worldinshadow_ActividadOpenAL_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_icecool_worldinshadow_ActividadOpenAL_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_AUTO_CREATE
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_AUTO_CREATE 1L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_DEBUG_UNBIND
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_DEBUG_UNBIND 2L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_NOT_FOREGROUND
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_NOT_FOREGROUND 4L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_ABOVE_CLIENT
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_ABOVE_CLIENT 8L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_ALLOW_OOM_MANAGEMENT
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_WAIVE_PRIORITY
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_WAIVE_PRIORITY 32L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_IMPORTANT
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_IMPORTANT 64L
#undef com_icecool_worldinshadow_ActividadOpenAL_BIND_ADJUST_WITH_ACTIVITY
#define com_icecool_worldinshadow_ActividadOpenAL_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_INCLUDE_CODE
#define com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_INCLUDE_CODE 1L
#undef com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_IGNORE_SECURITY
#define com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_IGNORE_SECURITY 2L
#undef com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_RESTRICTED
#define com_icecool_worldinshadow_ActividadOpenAL_CONTEXT_RESTRICTED 4L
#undef com_icecool_worldinshadow_ActividadOpenAL_RESULT_CANCELED
#define com_icecool_worldinshadow_ActividadOpenAL_RESULT_CANCELED 0L
#undef com_icecool_worldinshadow_ActividadOpenAL_RESULT_OK
#define com_icecool_worldinshadow_ActividadOpenAL_RESULT_OK -1L
#undef com_icecool_worldinshadow_ActividadOpenAL_RESULT_FIRST_USER
#define com_icecool_worldinshadow_ActividadOpenAL_RESULT_FIRST_USER 1L
#undef com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_DISABLE
#define com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_DISABLE 0L
#undef com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_DIALER
#define com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_DIALER 1L
#undef com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SHORTCUT
#define com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SHORTCUT 2L
#undef com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SEARCH_LOCAL
#define com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_icecool_worldinshadow_ActividadOpenAL_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    initOpenAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_initOpenAL
  (JNIEnv *, jobject);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    releaseOpenAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_releaseOpenAL
  (JNIEnv *, jobject);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    cargarBuffer
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_cargarBuffer
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    liberarBuffer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_liberarBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    crearFuente
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_crearFuente
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    playFuente
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_playFuente
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    pauseFuente
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_pauseFuente
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    stopFuente
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_stopFuente
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    liberarFuente
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_liberarFuente
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    estaReproduciendo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_estaReproduciendo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    setReceptor
 * Signature: (FFFFFFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_setReceptor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_icecool_worldinshadow_ActividadOpenAL
 * Method:    setEmisor
 * Signature: (IFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_icecool_worldinshadow_ActividadOpenAL_setEmisor
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
