/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_icecool_worldinshadow_ActividadOpenAL_MyRenderer */

#ifndef _Included_com_icecool_worldinshadow_ActividadOpenAL_MyRenderer
#define _Included_com_icecool_worldinshadow_ActividadOpenAL_MyRenderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
